### ISSUE TITLE
Plugin always forces update of SSL certificate "public" and brocadevtm_virtual_server "aptimizer", "dns" and "gzip" fields

### ISSUE THREAD

**Issue by ramalhais-sky** [sky-uk/terraform-provider-brocadevtm#117]
~ brocadevtm_ssl_server_key.mycert
      public:  "CERT_STUFF" => "CERT_STUFF"
~ brocadevtm_virtual_server.myvirtualserver
      aptimizer.#: "" => <computed>
      dns.#:       "" => <computed>
      gzip.#:      "" => <computed>

**Comment by grubert65** [comment]
The issue on the virtual server resource has been fixed, the one referring the certificates is still open, the only workaround being deleting the annotations from the certificates.
