### ISSUE TITLE
support for brocade vtm api version

### ISSUE THREAD

**Issue by iahmad-khan** [sky-uk/terraform-provider-brocadevtm#20]
Hi , 

Is it bound to a specific vtm api version such 3.5 or 4.0 etc?

If yes  , can we have the API version as a variable to any arbitrary value at our own risk?

thanks

**Comment by craig-duffin** [comment]
Currently the bindings it uses are hardcoded to 3.8, although in the next couple weeks this will be changed and there will be a method for the user specifying an API version. 
In the meantime I think it would be possible to use if you edited the endpoint variable in the resource files from 3.8 to whichever version you want in /vendor/github.com/sky-uk/go-brocade-vtm/api/

Allowing the user to specify version is something we 100% aim to implement quickly

**Comment by craig-duffin** [comment]
Hi, We now allow you to specify the API version using the providers "api_version" field. Alternatively you can set the the environment variable "BROCADEVTM_SERVER" to the version you use. This has not been tested upwards from version 3.8 so the provider may not work currently for every resource in 5.0 etc, but we are in the process of doing it, however versions 3.8 and below should function correctly.
