### ISSUE TITLE
Removing pool monitors doesn't apply a change

### ISSUE THREAD

**Issue by peterbale** [sky-uk/terraform-provider-brocadevtm#81]
When going from `monitors > 0` to `monitors = 0` the provider chooses not to set a slice of monitors which in turn doesn't change the original state (an existing monitor). The read method works as it's able to detect a change:

```
Terraform will perform the following actions:

  ~ brocadevtm_pool.lb
      monitors.#: "1" => "0"
      monitors.0: "Ping" => ""
```

However, when the apply is run it doesn't change the monitors to empty. This is likely due to the monitors value not being set to `[]string{}`. A fix is to manually remove monitors from the loadbalancer and terraform believes it is 'up to date'.

**Comment by craig-duffin** [comment]
This issue is fixed in release 0.4.20
